export const LOGIN_REQUEST ="LOGIN_REQUEST";
export const LOGIN_SUCCESS ="LOGIN_SUCCESS";
export const LOGIN_FAILURE ="LOGIN_FAILURE";


export const SIGNIN_REQUEST ="SIGNIN_REQUEST";
export const SIGNIN_SUCCESS ="SIGNIN_SUCCESS";
export const SIGNIN_FAILURE ="SIGNIN_FAILURE";


export const USERDATA_REQUEST = "USERDATA_REQUEST";
export const USERDATA_SUCCESS = "USERDATA_SUCCESS";
export const USERDATA_FAILURE = "USERDATA_FAILURE";



export const USERDATA_UPDATE_REQUEST = "USERDATA_UPDATE_REQUEST";
export const USERDATA_UPDATE = "USERDATA_UPDATE";
export const USERDATA_UPDATE_FAILURE = "USERDATA_UPDATE_FAILURE";




export const REMOVE_FROM_CART="REMOVE_FROM_CART";





export const IMAGE_URL_REQUEST = "IMAGE_URL_REQUEST";
export const IMAGE_URL_SUCCESS = "IMAGE_URL_SUCCESS";
export const IMAGE_URL_FAILURE = "IMAGE_URL_FAILURE";