export const LOGIN_REQUEST ="LOGIN_REQUEST";
export const LOGIN_SUCCESS ="LOGIN_SUCCESS";
export const LOGIN_FAILURE ="LOGIN_FAILURE";


export const SIGNIN_REQUEST ="SIGNIN_REQUEST";
export const SIGNIN_SUCCESS ="SIGNIN_SUCCESS";
export const SIGNIN_FAILURE ="SIGNIN_FAILURE";


export const USERDATA_REQUEST = "USERDATA_REQUEST";
export const USERDATA_SUCCESS = "USERDATA_SUCCESS";
export const USERDATA_FAILURE = "USERDATA_FAILURE";