export const GET_PROD_REQ = "GET_PROD_REQ"
export const GET_PROD_SUCCESS = "GET_PROD_SUCCESS"
export const GET_PROD_FAILURE = "GET_PROD_FAILURE"


export const GET_SEARCH_REQUEST="GET_SEARCH_REQUEST"
export const GET_SEARCH_SUCCESS="GET_SEARCH_SUCCESS"
export const GET_SEARCH_FAILURE="GET_SEARCH_FAILURE"
