export const GET_PROD_REQ = "GET_PROD_REQ"
export const GET_PROD_SUCCESS = "GET_PROD_SUCCESS"
export const GET_PROD_FAILURE = "GET_PROD_FAILURE"

export const ITEM_PRICE_QUANTITY = "ITEM_PRICE_QUANTITY"
