/* eslint-disable no-use-before-define */
import React from "react";
import TextField from "@material-ui/core/TextField";
import Autocomplete from "@material-ui/lab/Autocomplete";
import { makeStyles } from "@material-ui/core/styles";
import IconButton from "@material-ui/core/IconButton";
import {
  IconFlagAD,
  IconFlagAE,
  IconFlagAF,
  IconFlagAG,
  IconFlagAI,
  IconFlagAL,
  IconFlagAM,
  IconFlagAO,
  IconFlagAQ,
  IconFlagAR,
  IconFlagAS,
  IconFlagAT,
  IconFlagAU,
  IconFlagAW,
  IconFlagAX,
  IconFlagAZ,
  IconFlagBA,
  IconFlagBB,
  IconFlagBD,
  IconFlagBE,
  IconFlagBF,
  IconFlagBG,
  IconFlagBH,
  IconFlagBI,
  IconFlagBJ,
  IconFlagBL,
  IconFlagBM,
  IconFlagBN,
  IconFlagBO,
  IconFlagBR,
  IconFlagBS,
  IconFlagBT,
  IconFlagBV,
  IconFlagBW,
  IconFlagBY,
  IconFlagBZ,
  IconFlagCA,
  IconFlagCC,
  IconFlagCD,
  IconFlagCF,
  IconFlagCG,
  IconFlagCH,
  IconFlagCI,
  IconFlagCK,
  IconFlagCL,
  IconFlagCM,
  IconFlagCN,
  IconFlagCO,
  IconFlagCR,
  IconFlagCU,
  IconFlagCV,
  IconFlagCW,
  IconFlagCX,
  IconFlagCY,
  IconFlagCZ,
  IconFlagDE,
  IconFlagDJ,
  IconFlagDK,
  IconFlagDM,
  IconFlagDO,
  IconFlagDZ,
  IconFlagEC,
  IconFlagEE,
  IconFlagEG,
  IconFlagEH,
  IconFlagER,
  IconFlagES,
  IconFlagET,
  IconFlagFI,
  IconFlagFJ,
  IconFlagFK,
  IconFlagFM,
  IconFlagFO,
  IconFlagFR,
  IconFlagGA,
  IconFlagGB,
  IconFlagGD,
  IconFlagGE,
  IconFlagGF,
  IconFlagGG,
  IconFlagGH,
  IconFlagGI,
  IconFlagGL,
  IconFlagGM,
  IconFlagGN,
  IconFlagGP,
  IconFlagGQ,
  IconFlagGR,
  IconFlagGS,
  IconFlagGT,
  IconFlagGU,
  IconFlagGW,
  IconFlagGY,
  IconFlagHK,
  IconFlagHM,
  IconFlagHN,
  IconFlagHR,
  IconFlagHT,
  IconFlagHU,
  IconFlagID,
  IconFlagIE,
  IconFlagIL,
  IconFlagIM,
  IconFlagIN,
  IconFlagIO,
  IconFlagIQ,
  IconFlagIR,
  IconFlagIS,
  IconFlagIT,
  IconFlagJE,
  IconFlagJM,
  IconFlagJO,
  IconFlagJP,
  IconFlagKE,
  IconFlagKG,
  IconFlagKH,
  IconFlagKI,
  IconFlagKM,
  IconFlagKN,
  IconFlagKP,
  IconFlagKR,
  IconFlagKW,
  IconFlagKY,
  IconFlagKZ,
  IconFlagLA,
  IconFlagLB,
  IconFlagLC,
  IconFlagLI,
  IconFlagLK,
  IconFlagLR,
  IconFlagLS,
  IconFlagLT,
  IconFlagLU,
  IconFlagLV,
  IconFlagLY,
  IconFlagMA,
  IconFlagMC,
  IconFlagMD,
  IconFlagME,
  IconFlagMF,
  IconFlagMG,
  IconFlagMH,
  IconFlagMK,
  IconFlagML,
  IconFlagMM,
  IconFlagMN,
  IconFlagMO,
  IconFlagMP,
  IconFlagMQ,
  IconFlagMR,
  IconFlagMS,
  IconFlagMT,
  IconFlagMU,
  IconFlagMV,
  IconFlagMW,
  IconFlagMX,
  IconFlagMY,
  IconFlagMZ,
  IconFlagNA,
  IconFlagNC,
  IconFlagNE,
  IconFlagNF,
  IconFlagNG,
  IconFlagNI,
  IconFlagNL,
  IconFlagNO,
  IconFlagNP,
  IconFlagNR,
  IconFlagNU,
  IconFlagNZ,
  IconFlagOM,
  IconFlagPA,
  IconFlagPE,
  IconFlagPF,
  IconFlagPG,
  IconFlagPH,
  IconFlagPK,
  IconFlagPL,
  IconFlagPM,
  IconFlagPN,
  IconFlagPR,
  IconFlagPS,
  IconFlagPT,
  IconFlagPW,
  IconFlagPY,
  IconFlagQA,
  IconFlagRE,
  IconFlagRO,
  IconFlagRS,
  IconFlagRU,
  IconFlagRW,
  IconFlagSA,
  IconFlagSB,
  IconFlagSC,
  IconFlagSD,
  IconFlagSE,
  IconFlagSG,
  IconFlagSH,
  IconFlagSI,
  IconFlagSJ,
  IconFlagSK,
  IconFlagSL,
  IconFlagSM,
  IconFlagSN,
  IconFlagSO,
  IconFlagSR,
  IconFlagSS,
  IconFlagST,
  IconFlagSV,
  IconFlagSX,
  IconFlagSY,
  IconFlagSZ,
  IconFlagTC,
  IconFlagTD,
  IconFlagTF,
  IconFlagTG,
  IconFlagTH,
  IconFlagTJ,
  IconFlagTK,
  IconFlagTL,
  IconFlagTM,
  IconFlagTN,
  IconFlagTO,
  IconFlagTR,
  IconFlagTT,
  IconFlagTV,
  IconFlagTW,
  IconFlagTZ,
  IconFlagUA,
  IconFlagUG,
  IconFlagUS,
  IconFlagUY,
  IconFlagUZ,
  IconFlagVA,
  IconFlagVC,
  IconFlagVE,
  IconFlagVG,
  IconFlagVI,
  IconFlagVN,
  IconFlagVU,
  IconFlagWF,
  IconFlagWS,
  IconFlagXK,
  IconFlagYE,
  IconFlagYT,
  IconFlagZA,
  IconFlagZM,
  IconFlagZW,
} from "material-ui-flags";

function countryToFlag(isoCode) {
  return typeof String.fromCodePoint !== "undefined"
    ? isoCode
        .toUpperCase()
        .replace(/./g, (char) =>
          String.fromCodePoint(char.charCodeAt(0) + 127397)
        )
    : isoCode;
}

const useStyles = makeStyles({
  option: {
    fontSize: 15,
    "& > span": {
      marginRight: 10,
      fontSize: 18,
    },
  },
});

export default function CountrySelect() {
  const classes = useStyles();

  return (
    <Autocomplete
      id="country-select-demo"
      style={{ width: 300 }}
      options={countries}
      classes={{
        option: classes.option,
      }}
      autoHighlight
      getOptionLabel={(option) => option.label}
      renderOption={(option) => (
        <React.Fragment>
          <IconButton>
            <IconFlagIN />
          </IconButton>
          {option.label}
        </React.Fragment>
      )}
      renderInput={(params) => (
        <TextField
          style={{ border: "none" }}
          {...params}
          label={
            <IconButton>
              <IconFlagIN />
            </IconButton>
          }
          variant="outlined"
          inputProps={{
            ...params.inputProps,
            autoComplete: "new-password", // disable autocomplete and autofill
          }}
        />
      )}
    />
  );
}

// From https://bitbucket.org/atlassian/atlaskit-mk-2/raw/4ad0e56649c3e6c973e226b7efaeb28cb240ccb0/packages/core/select/src/data/countries.js
const countries = [
  { code: "AD", IconFlag: IconFlagAD, label: "Andorra", phone: "376" },
  {
    code: "AE",
    IconFlag: IconFlagAE,
    label: "United Arab Emirates",
    phone: "971",
  },
  { code: "AF", IconFlag: IconFlagAF, label: "Afghanistan", phone: "93" },
  {
    code: "AG",
    IconFlag: IconFlagAG,
    label: "Antigua and Barbuda",
    phone: "1-268",
  },
  { code: "AI", IconFlag: IconFlagAI, label: "Anguilla", phone: "1-264" },
  { code: "AL", IconFlag: IconFlagAL, label: "Albania", phone: "355" },
  { code: "AM", IconFlag: IconFlagAM, label: "Armenia", phone: "374" },
  { code: "AO", IconFlag: IconFlagAO, label: "Angola", phone: "244" },
  { code: "AQ", IconFlag: IconFlagAQ, label: "Antarctica", phone: "672" },
  { code: "AR", IconFlag: IconFlagAR, label: "Argentina", phone: "54" },
  { code: "AS", IconFlag: IconFlagAS, label: "American Samoa", phone: "1-684" },
  { code: "AT", IconFlag: IconFlagAT, label: "Austria", phone: "43" },
  {
    code: "AU",
    IconFlag: IconFlagAU,
    label: "Australia",
    phone: "61",
    suggested: true,
  },
  { code: "AW", IconFlag: IconFlagAW, label: "Aruba", phone: "297" },
  { code: "AX", IconFlag: IconFlagAX, label: "Alland Islands", phone: "358" },
  { code: "AZ", IconFlag: IconFlagAZ, label: "Azerbaijan", phone: "994" },
  {
    code: "BA",
    IconFlag: IconFlagBA,
    label: "Bosnia and Herzegovina",
    phone: "387",
  },
  { code: "BB", IconFlag: IconFlagBB, label: "Barbados", phone: "1-246" },
  { code: "BD", IconFlag: IconFlagBD, label: "Bangladesh", phone: "880" },
  { code: "BE", IconFlag: IconFlagBE, label: "Belgium", phone: "32" },
  { code: "BF", IconFlag: IconFlagBF, label: "Burkina Faso", phone: "226" },
  { code: "BG", IconFlag: IconFlagBG, label: "Bulgaria", phone: "359" },
  { code: "BH", IconFlag: IconFlagBH, label: "Bahrain", phone: "973" },
  { code: "BI", IconFlag: IconFlagBI, label: "Burundi", phone: "257" },
  { code: "BJ", IconFlag: IconFlagBJ, label: "Benin", phone: "229" },
  { code: "BL", IconFlag: IconFlagBL, label: "Saint Barthelemy", phone: "590" },
  { code: "BM", IconFlag: IconFlagBM, label: "Bermuda", phone: "1-441" },
  {
    code: "BN",
    IconFlag: IconFlagBN,
    label: "Brunei Darussalam",
    phone: "673",
  },
  { code: "BO", IconFlag: IconFlagBO, label: "Bolivia", phone: "591" },
  { code: "BR", IconFlag: IconFlagBR, label: "Brazil", phone: "55" },
  { code: "BS", IconFlag: IconFlagBS, label: "Bahamas", phone: "1-242" },
  { code: "BT", IconFlag: IconFlagBT, label: "Bhutan", phone: "975" },
  { code: "BV", IconFlag: IconFlagBV, label: "Bouvet Island", phone: "47" },
  { code: "BW", IconFlag: IconFlagBW, label: "Botswana", phone: "267" },
  { code: "BY", IconFlag: IconFlagBY, label: "Belarus", phone: "375" },
  { code: "BZ", IconFlag: IconFlagBZ, label: "Belize", phone: "501" },
  {
    code: "CA",
    IconFlag: IconFlagCA,
    label: "Canada",
    phone: "1",
    suggested: true,
  },
  {
    code: "CC",
    IconFlag: IconFlagCC,
    label: "Cocos (Keeling) Islands",
    phone: "61",
  },
  {
    code: "CD",
    IconFlag: IconFlagCD,
    label: "Congo, Democratic Republic of the",
    phone: "243",
  },
  {
    code: "CF",
    IconFlag: IconFlagCF,
    label: "Central African Republic",
    phone: "236",
  },
  {
    code: "CG",
    IconFlag: IconFlagCG,
    label: "Congo, Republic of the",
    phone: "242",
  },
  { code: "CH", IconFlag: IconFlagCH, label: "Switzerland", phone: "41" },
  { code: "CI", IconFlag: IconFlagCI, label: "Cote d'Ivoire", phone: "225" },
  { code: "CK", IconFlag: IconFlagCK, label: "Cook Islands", phone: "682" },
  { code: "CL", IconFlag: IconFlagCL, label: "Chile", phone: "56" },
  { code: "CM", IconFlag: IconFlagCM, label: "Cameroon", phone: "237" },
  { code: "CN", IconFlag: IconFlagCN, label: "China", phone: "86" },
  { code: "CO", IconFlag: IconFlagCO, label: "Colombia", phone: "57" },
  { code: "CR", IconFlag: IconFlagCR, label: "Costa Rica", phone: "506" },
  { code: "CU", IconFlag: IconFlagCU, label: "Cuba", phone: "53" },
  { code: "CV", IconFlag: IconFlagCV, label: "Cape Verde", phone: "238" },
  { code: "CW", IconFlag: IconFlagCW, label: "Curacao", phone: "599" },
  { code: "CX", IconFlag: IconFlagCX, label: "Christmas Island", phone: "61" },
  { code: "CY", IconFlag: IconFlagCY, label: "Cyprus", phone: "357" },
  { code: "CZ", IconFlag: IconFlagCZ, label: "Czech Republic", phone: "420" },
  {
    code: "DE",
    IconFlag: IconFlagDE,
    label: "Germany",
    phone: "49",
    suggested: true,
  },
  { code: "DJ", IconFlag: IconFlagDJ, label: "Djibouti", phone: "253" },
  { code: "DK", IconFlag: IconFlagDK, label: "Denmark", phone: "45" },
  { code: "DM", IconFlag: IconFlagDM, label: "Dominica", phone: "1-767" },
  {
    code: "DO",
    IconFlag: IconFlagDO,
    label: "Dominican Republic",
    phone: "1-809",
  },
  { code: "DZ", IconFlag: IconFlagDZ, label: "Algeria", phone: "213" },
  { code: "EC", IconFlag: IconFlagEC, label: "Ecuador", phone: "593" },
  { code: "EE", IconFlag: IconFlagEE, label: "Estonia", phone: "372" },
  { code: "EG", IconFlag: IconFlagEG, label: "Egypt", phone: "20" },
  { code: "EH", IconFlag: IconFlagEH, label: "Western Sahara", phone: "212" },
  { code: "ER", IconFlag: IconFlagER, label: "Eritrea", phone: "291" },
  { code: "ES", IconFlag: IconFlagES, label: "Spain", phone: "34" },
  { code: "ET", IconFlag: IconFlagET, label: "Ethiopia", phone: "251" },
  { code: "FI", IconFlag: IconFlagFI, label: "Finland", phone: "358" },
  { code: "FJ", IconFlag: IconFlagFJ, label: "Fiji", phone: "679" },
  {
    code: "FK",
    IconFlag: IconFlagFK,
    label: "Falkland Islands (Malvinas)",
    phone: "500",
  },
  {
    code: "FM",
    IconFlag: IconFlagFM,
    label: "Micronesia, Federated States of",
    phone: "691",
  },
  { code: "FO", IconFlag: IconFlagFO, label: "Faroe Islands", phone: "298" },
  {
    code: "FR",
    IconFlag: IconFlagFR,
    label: "France",
    phone: "33",
    suggested: true,
  },
  { code: "GA", IconFlag: IconFlagGA, label: "Gabon", phone: "241" },
  { code: "GB", IconFlag: IconFlagGB, label: "United Kingdom", phone: "44" },
  { code: "GD", IconFlag: IconFlagGD, label: "Grenada", phone: "1-473" },
  { code: "GE", IconFlag: IconFlagGE, label: "Georgia", phone: "995" },
  { code: "GF", IconFlag: IconFlagGF, label: "French Guiana", phone: "594" },
  { code: "GG", IconFlag: IconFlagGG, label: "Guernsey", phone: "44" },
  { code: "GH", IconFlag: IconFlagGH, label: "Ghana", phone: "233" },
  { code: "GI", IconFlag: IconFlagGI, label: "Gibraltar", phone: "350" },
  { code: "GL", IconFlag: IconFlagGL, label: "Greenland", phone: "299" },
  { code: "GM", IconFlag: IconFlagGM, label: "Gambia", phone: "220" },
  { code: "GN", IconFlag: IconFlagGN, label: "Guinea", phone: "224" },
  { code: "GP", IconFlag: IconFlagGP, label: "Guadeloupe", phone: "590" },
  {
    code: "GQ",
    IconFlag: IconFlagGQ,
    label: "Equatorial Guinea",
    phone: "240",
  },
  { code: "GR", IconFlag: IconFlagGR, label: "Greece", phone: "30" },
  {
    code: "GS",
    IconFlag: IconFlagGS,
    label: "South Georgia and the South Sandwich Islands",
    phone: "500",
  },
  { code: "GT", IconFlag: IconFlagGT, label: "Guatemala", phone: "502" },
  { code: "GU", IconFlag: IconFlagGU, label: "Guam", phone: "1-671" },
  { code: "GW", IconFlag: IconFlagGW, label: "Guinea-Bissau", phone: "245" },
  { code: "GY", IconFlag: IconFlagGY, label: "Guyana", phone: "592" },
  { code: "HK", IconFlag: IconFlagHK, label: "Hong Kong", phone: "852" },
  {
    code: "HM",
    IconFlag: IconFlagHM,
    label: "Heard Island and McDonald Islands",
    phone: "672",
  },
  { code: "HN", IconFlag: IconFlagHN, label: "Honduras", phone: "504" },
  { code: "HR", IconFlag: IconFlagHR, label: "Croatia", phone: "385" },
  { code: "HT", IconFlag: IconFlagHT, label: "Haiti", phone: "509" },
  { code: "HU", IconFlag: IconFlagHU, label: "Hungary", phone: "36" },
  { code: "ID", IconFlag: IconFlagID, label: "Indonesia", phone: "62" },
  { code: "IE", IconFlag: IconFlagIE, label: "Ireland", phone: "353" },
  { code: "IL", IconFlag: IconFlagIL, label: "Israel", phone: "972" },
  { code: "IM", IconFlag: IconFlagIM, label: "Isle of Man", phone: "44" },
  { code: "IN", IconFlag: IconFlagIN, label: "India", phone: "91" },
  {
    code: "IO",
    IconFlag: IconFlagIO,
    label: "British Indian Ocean Territory",
    phone: "246",
  },
  { code: "IQ", IconFlag: IconFlagIQ, label: "Iraq", phone: "964" },
  {
    code: "IR",
    IconFlag: IconFlagIR,
    label: "Iran, Islamic Republic of",
    phone: "98",
  },
  { code: "IS", IconFlag: IconFlagIS, label: "Iceland", phone: "354" },
  { code: "IT", IconFlag: IconFlagIT, label: "Italy", phone: "39" },
  { code: "JE", IconFlag: IconFlagJE, label: "Jersey", phone: "44" },
  { code: "JM", IconFlag: IconFlagJM, label: "Jamaica", phone: "1-876" },
  { code: "JO", IconFlag: IconFlagJO, label: "Jordan", phone: "962" },
  {
    code: "JP",
    IconFlag: IconFlagJP,
    label: "Japan",
    phone: "81",
    suggested: true,
  },
  { code: "KE", IconFlag: IconFlagKE, label: "Kenya", phone: "254" },
  { code: "KG", IconFlag: IconFlagKG, label: "Kyrgyzstan", phone: "996" },
  { code: "KH", IconFlag: IconFlagKH, label: "Cambodia", phone: "855" },
  { code: "KI", IconFlag: IconFlagKI, label: "Kiribati", phone: "686" },
  { code: "KM", IconFlag: IconFlagKM, label: "Comoros", phone: "269" },
  {
    code: "KN",
    IconFlag: IconFlagKN,
    label: "Saint Kitts and Nevis",
    phone: "1-869",
  },
  {
    code: "KP",
    IconFlag: IconFlagKP,
    label: "Korea, Democratic People's Republic of",
    phone: "850",
  },
  {
    code: "KR",
    IconFlag: IconFlagKR,
    label: "Korea, Republic of",
    phone: "82",
  },
  { code: "KW", IconFlag: IconFlagKW, label: "Kuwait", phone: "965" },
  { code: "KY", IconFlag: IconFlagKY, label: "Cayman Islands", phone: "1-345" },
  { code: "KZ", IconFlag: IconFlagKZ, label: "Kazakhstan", phone: "7" },
  {
    code: "LA",
    IconFlag: IconFlagLA,
    label: "Lao People's Democratic Republic",
    phone: "856",
  },
  { code: "LB", IconFlag: IconFlagLB, label: "Lebanon", phone: "961" },
  { code: "LC", IconFlag: IconFlagLC, label: "Saint Lucia", phone: "1-758" },
  { code: "LI", IconFlag: IconFlagLI, label: "Liechtenstein", phone: "423" },
  { code: "LK", IconFlag: IconFlagLK, label: "Sri Lanka", phone: "94" },
  { code: "LR", IconFlag: IconFlagLR, label: "Liberia", phone: "231" },
  { code: "LS", IconFlag: IconFlagLS, label: "Lesotho", phone: "266" },
  { code: "LT", IconFlag: IconFlagLT, label: "Lithuania", phone: "370" },
  { code: "LU", IconFlag: IconFlagLU, label: "Luxembourg", phone: "352" },
  { code: "LV", IconFlag: IconFlagLV, label: "Latvia", phone: "371" },
  { code: "LY", IconFlag: IconFlagLY, label: "Libya", phone: "218" },
  { code: "MA", IconFlag: IconFlagMA, label: "Morocco", phone: "212" },
  { code: "MC", IconFlag: IconFlagMC, label: "Monaco", phone: "377" },
  {
    code: "MD",
    IconFlag: IconFlagMD,
    label: "Moldova, Republic of",
    phone: "373",
  },
  { code: "ME", IconFlag: IconFlagME, label: "Montenegro", phone: "382" },
  {
    code: "MF",
    IconFlag: IconFlagMF,
    label: "Saint Martin (French part)",
    phone: "590",
  },
  { code: "MG", IconFlag: IconFlagMG, label: "Madagascar", phone: "261" },
  { code: "MH", IconFlag: IconFlagMH, label: "Marshall Islands", phone: "692" },
  {
    code: "MK",
    IconFlag: IconFlagMK,
    label: "Macedonia, the Former Yugoslav Republic of",
    phone: "389",
  },
  { code: "ML", IconFlag: IconFlagML, label: "Mali", phone: "223" },
  { code: "MM", IconFlag: IconFlagMM, label: "Myanmar", phone: "95" },
  { code: "MN", IconFlag: IconFlagMN, label: "Mongolia", phone: "976" },
  { code: "MO", IconFlag: IconFlagMO, label: "Macao", phone: "853" },
  {
    code: "MP",
    IconFlag: IconFlagMP,
    label: "Northern Mariana Islands",
    phone: "1-670",
  },
  { code: "MQ", IconFlag: IconFlagMQ, label: "Martinique", phone: "596" },
  { code: "MR", IconFlag: IconFlagMR, label: "Mauritania", phone: "222" },
  { code: "MS", IconFlag: IconFlagMS, label: "Montserrat", phone: "1-664" },
  { code: "MT", IconFlag: IconFlagMT, label: "Malta", phone: "356" },
  { code: "MU", IconFlag: IconFlagMU, label: "Mauritius", phone: "230" },
  { code: "MV", IconFlag: IconFlagMV, label: "Maldives", phone: "960" },
  { code: "MW", IconFlag: IconFlagMW, label: "Malawi", phone: "265" },
  { code: "MX", IconFlag: IconFlagMX, label: "Mexico", phone: "52" },
  { code: "MY", IconFlag: IconFlagMY, label: "Malaysia", phone: "60" },
  { code: "MZ", IconFlag: IconFlagMZ, label: "Mozambique", phone: "258" },
  { code: "NA", IconFlag: IconFlagNA, label: "Namibia", phone: "264" },
  { code: "NC", IconFlag: IconFlagNC, label: "New Caledonia", phone: "687" },
  { code: "NE", IconFlag: IconFlagNE, label: "Niger", phone: "227" },
  { code: "NF", IconFlag: IconFlagNF, label: "Norfolk Island", phone: "672" },
  { code: "NG", IconFlag: IconFlagNG, label: "Nigeria", phone: "234" },
  { code: "NI", IconFlag: IconFlagNI, label: "Nicaragua", phone: "505" },
  { code: "NL", IconFlag: IconFlagNL, label: "Netherlands", phone: "31" },
  { code: "NO", IconFlag: IconFlagNO, label: "Norway", phone: "47" },
  { code: "NP", IconFlag: IconFlagNP, label: "Nepal", phone: "977" },
  { code: "NR", IconFlag: IconFlagNR, label: "Nauru", phone: "674" },
  { code: "NU", IconFlag: IconFlagNU, label: "Niue", phone: "683" },
  { code: "NZ", IconFlag: IconFlagNZ, label: "New Zealand", phone: "64" },
  { code: "OM", IconFlag: IconFlagOM, label: "Oman", phone: "968" },
  { code: "PA", IconFlag: IconFlagPA, label: "Panama", phone: "507" },
  { code: "PE", IconFlag: IconFlagPE, label: "Peru", phone: "51" },
  { code: "PF", IconFlag: IconFlagPF, label: "French Polynesia", phone: "689" },
  { code: "PG", IconFlag: IconFlagPG, label: "Papua New Guinea", phone: "675" },
  { code: "PH", IconFlag: IconFlagPH, label: "Philippines", phone: "63" },
  { code: "PK", IconFlag: IconFlagPK, label: "Pakistan", phone: "92" },
  { code: "PL", IconFlag: IconFlagPL, label: "Poland", phone: "48" },
  {
    code: "PM",
    IconFlag: IconFlagPM,
    label: "Saint Pierre and Miquelon",
    phone: "508",
  },
  { code: "PN", IconFlag: IconFlagPN, label: "Pitcairn", phone: "870" },
  { code: "PR", IconFlag: IconFlagPR, label: "Puerto Rico", phone: "1" },
  {
    code: "PS",
    IconFlag: IconFlagPS,
    label: "Palestine, State of",
    phone: "970",
  },
  { code: "PT", IconFlag: IconFlagPT, label: "Portugal", phone: "351" },
  { code: "PW", IconFlag: IconFlagPW, label: "Palau", phone: "680" },
  { code: "PY", IconFlag: IconFlagPY, label: "Paraguay", phone: "595" },
  { code: "QA", IconFlag: IconFlagQA, label: "Qatar", phone: "974" },
  { code: "RE", IconFlag: IconFlagRE, label: "Reunion", phone: "262" },
  { code: "RO", IconFlag: IconFlagRO, label: "Romania", phone: "40" },
  { code: "RS", IconFlag: IconFlagRS, label: "Serbia", phone: "381" },
  { code: "RU", IconFlag: IconFlagRU, label: "Russian Federation", phone: "7" },
  { code: "RW", IconFlag: IconFlagRW, label: "Rwanda", phone: "250" },
  { code: "SA", IconFlag: IconFlagSA, label: "Saudi Arabia", phone: "966" },
  { code: "SB", IconFlag: IconFlagSB, label: "Solomon Islands", phone: "677" },
  { code: "SC", IconFlag: IconFlagSC, label: "Seychelles", phone: "248" },
  { code: "SD", IconFlag: IconFlagSD, label: "Sudan", phone: "249" },
  { code: "SE", IconFlag: IconFlagSE, label: "Sweden", phone: "46" },
  { code: "SG", IconFlag: IconFlagSG, label: "Singapore", phone: "65" },
  { code: "SH", IconFlag: IconFlagSH, label: "Saint Helena", phone: "290" },
  { code: "SI", IconFlag: IconFlagSI, label: "Slovenia", phone: "386" },
  {
    code: "SJ",
    IconFlag: IconFlagSJ,
    label: "Svalbard and Jan Mayen",
    phone: "47",
  },
  { code: "SK", IconFlag: IconFlagSK, label: "Slovakia", phone: "421" },
  { code: "SL", IconFlag: IconFlagSL, label: "Sierra Leone", phone: "232" },
  { code: "SM", IconFlag: IconFlagSM, label: "San Marino", phone: "378" },
  { code: "SN", IconFlag: IconFlagSN, label: "Senegal", phone: "221" },
  { code: "SO", IconFlag: IconFlagSO, label: "Somalia", phone: "252" },
  { code: "SR", IconFlag: IconFlagSR, label: "Suriname", phone: "597" },
  { code: "SS", IconFlag: IconFlagSS, label: "South Sudan", phone: "211" },
  {
    code: "ST",
    IconFlag: IconFlagST,
    label: "Sao Tome and Principe",
    phone: "239",
  },
  { code: "SV", IconFlag: IconFlagSV, label: "El Salvador", phone: "503" },
  {
    code: "SX",
    IconFlag: IconFlagSX,
    label: "Sint Maarten (Dutch part)",
    phone: "1-721",
  },
  {
    code: "SY",
    IconFlag: IconFlagSY,
    label: "Syrian Arab Republic",
    phone: "963",
  },
  { code: "SZ", IconFlag: IconFlagSZ, label: "Swaziland", phone: "268" },
  {
    code: "TC",
    IconFlag: IconFlagTC,
    label: "Turks and Caicos Islands",
    phone: "1-649",
  },
  { code: "TD", IconFlag: IconFlagTD, label: "Chad", phone: "235" },
  {
    code: "TF",
    IconFlag: IconFlagTF,
    label: "French Southern Territories",
    phone: "262",
  },
  { code: "TG", IconFlag: IconFlagTG, label: "Togo", phone: "228" },
  { code: "TH", IconFlag: IconFlagTH, label: "Thailand", phone: "66" },
  { code: "TJ", IconFlag: IconFlagTJ, label: "Tajikistan", phone: "992" },
  { code: "TK", IconFlag: IconFlagTK, label: "Tokelau", phone: "690" },
  { code: "TL", IconFlag: IconFlagTL, label: "Timor-Leste", phone: "670" },
  { code: "TM", IconFlag: IconFlagTM, label: "Turkmenistan", phone: "993" },
  { code: "TN", IconFlag: IconFlagTN, label: "Tunisia", phone: "216" },
  { code: "TO", IconFlag: IconFlagTO, label: "Tonga", phone: "676" },
  { code: "TR", IconFlag: IconFlagTR, label: "Turkey", phone: "90" },
  {
    code: "TT",
    IconFlag: IconFlagTT,
    label: "Trinidad and Tobago",
    phone: "1-868",
  },
  { code: "TV", IconFlag: IconFlagTV, label: "Tuvalu", phone: "688" },
  {
    code: "TW",
    IconFlag: IconFlagTW,
    label: "Taiwan, Province of China",
    phone: "886",
  },
  {
    code: "TZ",
    IconFlag: IconFlagTZ,
    label: "United Republic of Tanzania",
    phone: "255",
  },
  { code: "UA", IconFlag: IconFlagUA, label: "Ukraine", phone: "380" },
  { code: "UG", IconFlag: IconFlagUG, label: "Uganda", phone: "256" },
  {
    code: "US",
    IconFlag: IconFlagUS,
    label: "United States",
    phone: "1",
    suggested: true,
  },
  { code: "UY", IconFlag: IconFlagUY, label: "Uruguay", phone: "598" },
  { code: "UZ", IconFlag: IconFlagUZ, label: "Uzbekistan", phone: "998" },
  {
    code: "VA",
    IconFlag: IconFlagVA,
    label: "Holy See (Vatican City State)",
    phone: "379",
  },
  {
    code: "VC",
    IconFlag: IconFlagVC,
    label: "Saint Vincent and the Grenadines",
    phone: "1-784",
  },
  { code: "VE", IconFlag: IconFlagVE, label: "Venezuela", phone: "58" },
  {
    code: "VG",
    IconFlag: IconFlagVG,
    label: "British Virgin Islands",
    phone: "1-284",
  },
  {
    code: "VI",
    IconFlag: IconFlagVI,
    label: "US Virgin Islands",
    phone: "1-340",
  },
  { code: "VN", IconFlag: IconFlagVN, label: "Vietnam", phone: "84" },
  { code: "VU", IconFlag: IconFlagVU, label: "Vanuatu", phone: "678" },
  {
    code: "WF",
    IconFlag: IconFlagWF,
    label: "Wallis and Futuna",
    phone: "681",
  },
  { code: "WS", IconFlag: IconFlagWS, label: "Samoa", phone: "685" },
  { code: "XK", IconFlag: IconFlagXK, label: "Kosovo", phone: "383" },
  { code: "YE", IconFlag: IconFlagYE, label: "Yemen", phone: "967" },
  { code: "YT", IconFlag: IconFlagYT, label: "Mayotte", phone: "262" },
  { code: "ZA", IconFlag: IconFlagZA, label: "South Africa", phone: "27" },
  { code: "ZM", IconFlag: IconFlagZM, label: "Zambia", phone: "260" },
  { code: "ZW", IconFlag: IconFlagZW, label: "Zimbabwe", phone: "263" },
];
